[package]
name = "nexora-common"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "time", "macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt", "json"] }
tracing-appender = "0.2"
rand = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
regex = { workspace = true }
parking_lot = { workspace = true }
