# warn — pedantic but not blocking
cognitive-complexity-threshold = 18
too-many-arguments-threshold = 8
too-many-lines-threshold = 400
type-complexity-threshold = 200

# allow
allow-dbg-in-tests = false
allow-print-in-tests = false
allow-unwrap-in-tests = false
