[package]
name = "nexora-star-x"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
rand = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
once_cell = { workspace = true }
half = "2"
num_cpus = "1.16"
itertools = { workspace = true }
nexora-autograd = { path = "../autograd", optional = true, features = ["gpu"] }

[features]
default = ["std"]
std = []
gpu = ["nexora-autograd"]
full = ["std", "gpu"]
